---
- name: yum install the epel repo
  yum:
    name: epel-release
    state: latest

- name: install tsinghua epel repo
  yum_repository:
    name: epel
    description: 'Extra Packages for Enterprise Linux $releasever - $basearch'
    file: epel
    baseurl: 'https://mirrors.tuna.tsinghua.edu.cn/epel/$releasever/$basearch'
    gpgcheck: yes
    enabled: yes
    failovermethod: priority
    gpgkey: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-$releasever'

- name: install tsinghua epel-debuginfo repo
  yum_repository:
    name: epel-debuginfo
    description: 'Extra Packages for Enterprise Linux $releasever - $basearch - Debug'
    file: epel
    baseurl: 'https://mirrors.tuna.tsinghua.edu.cn/epel/$releasever/$basearch/debug'
    gpgcheck: yes
    enabled: no
    failovermethod: priority
    gpgkey: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-$releasever'

- name: install tsinghua epel-source repo
  yum_repository:
    name: epel-source
    description: 'Extra Packages for Enterprise Linux $releasever - $basearch - Source'
    file: epel
    baseurl: 'https://mirrors.tuna.tsinghua.edu.cn/epel/$releasever/SRPMS'
    gpgcheck: yes
    enabled: no
    failovermethod: priority
    gpgkey: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-$releasever'

- name: config tsinghua mongodb mirror
  yum_repository:
    name: mongodb-org
    description: 'Mongodb china YUM repo'
    file: mongodb
    baseurl: 'https://mirrors.tuna.tsinghua.edu.cn/mongodb/yum/el$releasever-4.0/'
    gpgcheck: no
    enabled: yes
  notify: yum-clean-metadata


- name: yum install the ntp
  yum:
    name: ntp
    state: latest
    enablerepo: epel

- name: update the time
  shell: ntpdate ntp1.aliyun.com

- name: add crontab
  cron:
    name: "ntpate"
    minute: "0"
    hour: "*/6"
    job: "ntpdate ntp1.aliyun.com >/dev/null 2>&1"

- name: uninstall the openjdk
  yum:
    name: java*
    state: absent
  tags: removejdk

- name: install the openjdk specific version
  yum:
    name: "java-{{ jdk_version }}"
    state: latest
    enablerepo: epel
  tags: installjdk

- name: yum  Development tools
  yum: 
    name: "@Development tools" 
    state: present

- name: other tools
  yum:
    name: [screen,telnet,parted,python-pip,nodejs]
    state: latest

- name: create the pip dir
  tags:
    - pip
  file:
    path: $HOME/.pip/
    state: directory

- name: copy the pip.conf
  tags:
    - pip
  copy:
    src: pip.conf
    dest: $HOME/.pip/pip.conf

- name: upgrade pip
  tags:
    - pip
  shell: pip install --upgrade pip

- name: install the pymongo
  tags:
    - pip
  pip:
    name: pymongo 

- name: update openssl
  yum:
    name: openssl
    state: latest

- name: 