---
- name: download the cdh master rpms
  tags:
    - install
  get_url:
    url: "{{ item.url }}"
    dest: "{{ download_dir }}/{{ item.name }}.rpm"
    timeout: 300
  loop: "{{ cdh_master }}"
  when: role == 'master'

- name: install the master rpms
  tags:
    - install
  yum:
    name: "{{ download_dir }}/{{item.name}}.rpm"
    state: present
  loop: "{{ cdh_master }}"
  when: role == 'master'

- name: set the master db conf
  tags:
    - dbconf
  template:
    src: db.properties.j2
    dest: /etc/cloudera-scm-server/db.properties
    owner: cloudera-scm
    group: cloudera-scm
    force: yes
  when: role == 'master'

- name: download parcel
  tags:
    - parcel
  get_url:
    url: "{{ parcel_url }}"
    dest: "/opt/cloudera/parcel-repo"
    timeout: 300
    owner: cloudera-scm
    group: cloudera-scm
  when: role == 'master'

- name: download parcel sha
  tags:
    - parcel
  get_url:
    url: "{{ parcel_sha_url }}"
    dest: "/opt/cloudera/parcel-repo/{{ parcel_sha_name }}"
    owner: cloudera-scm
    group: cloudera-scm
  when: role == 'master'


- name: download the cdh agent rpms
  tags:
    - install
  get_url:
    url: "{{ item.url }}"
    dest: "{{ download_dir }}/{{ item.name }}.rpm"
    timeout: 300
  loop: "{{ cdh_agent }}"
  when: role == 'agent'

- name: install the agent rpms
  tags:
    - install
  yum:
    name: "{{ download_dir }}/{{item.name}}.rpm"
    state: present
  loop: "{{ cdh_agent }}"
  when: role == 'agent'

- name: start the master server
  service:
    name: cloudera-scm-server
    state: started
  when: role == 'master'

- name: start the agent server
  service:
    name: cloudera-scm-agent
    state: started
  when: role == 'agent'
