---
# Variables here are applicable to all host groups

dev:
  - name: /dev/vdb1
    dir: /cache1
    label: LABEL=/cache1
    fstype: xfs
    opts: -d agcount={{ ansible_processor|length//3 }} -L /cache1

  - name: /dev/vdb2
    dir: /cache2
    label: LABEL=/cache2
    fstype: xfs
    opts: -d agcount={{ ansible_processor|length//3 }} -L /cache2

  - name: /dev/vdb3
    dir: /cache3
    label: LABEL=/cache3
    fstype: xfs
    opts: -d agcount={{ ansible_processor|length//3 }} -L /cache3