---
- name: install the cdh
  hosts: cdh
  gather_facts: no
  any_errors_fatal: no
  tags:
    - install_cdh
  tasks:
    - name: tomcat log
      blockinfile:
        path: "{{ item }}"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->" 
        block: |
            <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs" 
                prefix="localhost_access_log." suffix=".txt" pattern="common" resolveHosts="false"/>
        insertbefore: '</Host>'
        backup: yes
      ignore_errors: yes
      loop:
        - /var/lib/oozie/tomcat-deployment/conf/server.xml
        - /var/lib/hadoop-httpfs/tomcat-deployment/conf/server.xml
     
    - name: httpd ServerSignature
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: 'ServerSignature On'
        replace: 'ServerSignature Off'
        backup: yes
      ignore_errors: yes
    - name: httpd Indexes
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: 'Options Indexes FollowSymLinks'
        replace: 'Options -Indexes FollowSymLinks'
      ignore_errors: yes
    - name: httpd ssl SSLProtocol
      replace:
        path: /etc/httpd/conf.d/ssl.conf
        regexp: 'SSLProtocol all -SSLv2'
        replace: 'SSLProtocol All -SSLv2 -SSLv3'
        backup: yes
      ignore_errors: yes
    
    - name: httpd ssl SSLCipherSuite
      lineinfile:
        path: /etc/httpd/conf.d/ssl.conf
        regexp: 'SSLCipherSuite'
        line: SSLCipherSuite ECDHE-RSA-AES256-SHA384:AES256-SHA256:!RC4:HIGH:!MD5:!aNULL:!eNULL:!NULL:!DH:!EDH:!AESGCM
      ignore_errors: yes

    - name: commons-fileupload
      copy:
        src: commons-fileupload-1.4.jar
        dest: /usr/share/cmf/common_jars
    
    - name: delete the commons-fileupload-1.2.2.jar link
      file:
        path: /usr/share/cmf/lib/commons-fileupload-1.2.2.jar
        state: absent
      ignore_errors: yes
    
    - name: create the link
      file:
        src: /usr/share/cmf/common_jars/commons-fileupload-1.4.jar
        dest: /usr/share/cmf/lib/commons-fileupload-1.4.jar
        state: link
      ignore_errors: yes

    - name: commons-fileupload
      copy:
        src: commons-fileupload-1.4.jar
        dest: /var/lib/solr/tomcat-deployment/webapps/solr/WEB-INF/lib
      ignore_errors: yes