---
# Variables here are applicable to all host groups

dev:
  - name: /dev/vdb1
    dir: /cache1
    label: LABEL=/cache1
    fstype: xfs
    opts: -d agcount={{ ansible_processor|length//3 }} -L /cache1