---
- name: uninstall the openjdk
  yum:
    name: java*
    state: absent
  tags: removejdk

- name: install the  java jdk specific version
  yum:
    name: "{{ jdk_url }}"
    state: latest
  tags: installjdk

- name: set the path
  blockinfile:
    path: /etc/profile.d/java.sh
    marker: "# {mark} JAVA JDK"
    block: |
      export JAVA_HOME=/usr/java/jdk1.8.0_162
      export JRE_HOME=$JAVA_HOME/jre
      export CLASSPATH=.:$JAVA_HOME/lib:$JRE_HOME/lib
      export PATH=$PATH:$JAVA_HOME/bin
    create: yes

- name: reload the profile
  shell: source /etc/profile 

- name: create the jdbc dir
  file:
    path: /usr/share/java
    state: directory

- name: intall the jdbc
  copy:
    src: mysql-connector-java-5.1.46-bin.jar
    dest: /usr/share/java/mysql-connector-java.jar

