---
- name: unmount filesystem
  tags:
    - umount
  mount:
    path: "{{ item.dir }}"
    state: unmounted
  loop: "{{ dev_old }}"

- name: unmount filesystem
  tags:
    - umount
  mount:
    path: "{{ item.dir }}"
    state: absent
  loop: "{{ dev_old }}"

- name: delete old partitions
  parted:
    device: "{{ item.device }}"
    number: "{{ item.num }}"
    state: absent
  loop: "{{ dev_old }}"

- name: parted the disk
  parted:
    device: "{{ item.device }}"
    label: "{{ item.label }}"
    part_type: "{{ item.part_type }}"
    number: "{{ item.num }}"
    part_start: "{{ item.part_start }}"
    part_end: "{{ item.part_end }}"
    state: present
  loop: "{{ partitions }}"
